spring.application.name=Banking_System

# Profile activation
spring.profiles.active=dev

# JWT Settings (common)
jwt.expiration-ms=86400000  

# JPA common settings
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false     

# Actuator / Management (optional but recommended)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Virtual threads (Java 21+ feature, good for concurrency)
spring.threads.virtual.enabled=true