spring.application.name=Banking_System

spring.profiles.active=dev

jwt.expiration-ms=86400000

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.threads.virtual.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.try-it-out-enabled=true

spring.data.redis.host=localhost
spring.data.redis.port=6379