-- =====================================================================
-- V1: Create users table
-- Backs com.banking.model.User
-- =====================================================================

CREATE TABLE users (
                       id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       full_name VARCHAR(255) NOT NULL,
                       email     VARCHAR(255) NOT NULL,
                       password  VARCHAR(255) NOT NULL,

                       CONSTRAINT uk_users_email UNIQUE (email)
);

COMMENT ON TABLE users IS 'Application users / bank customers';
COMMENT ON COLUMN users.password IS 'BCrypt-hashed password, never stored in plaintext';