CREATE TABLE accounts (
                          id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          account_number VARCHAR(64) NOT NULL,
                          account_type   VARCHAR(20) NOT NULL,
                          balance        NUMERIC(19, 2) NOT NULL DEFAULT 0.00,
                          user_id        BIGINT NOT NULL,
                          version        BIGINT NOT NULL DEFAULT 0,

                          CONSTRAINT uk_accounts_account_number UNIQUE (account_number),
                          CONSTRAINT fk_accounts_user FOREIGN KEY (user_id)
                              REFERENCES users (id) ON DELETE CASCADE,
                          CONSTRAINT ck_accounts_account_type
                              CHECK (account_type IN ('SAVINGS', 'CURRENT')),
                          CONSTRAINT ck_accounts_balance_non_negative
                              CHECK (balance >= 0)
);

CREATE INDEX idx_accounts_user_id ON accounts (user_id);

COMMENT ON TABLE accounts IS 'Bank accounts owned by a user; balance mutations use optimistic (version) and pessimistic (findByIdForUpdate) locking';
COMMENT ON COLUMN accounts.version IS 'Optimistic locking column mapped by @Version on the Account entity';