-- =====================================================================
-- V3: Create transactions table
-- Backs com.banking.model.Transaction
-- transaction_type mirrors com.banking.model.TransactionType (DEPOSIT, WITHDRAW, TRANSFER)
-- status mirrors com.banking.model.TransactionStatus (PENDING, SUCCESS, FAILED)
--
-- sender_account_id / receiver_account_id are nullable by design:
--   DEPOSIT  -> sender_account_id IS NULL
--   WITHDRAW -> receiver_account_id IS NULL
--   TRANSFER -> both populated
-- (see TransactionServiceImpl null-checks on senderAccount/receiverAccount)
-- =====================================================================

CREATE TABLE transactions (
                              id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              transaction_type    VARCHAR(20) NOT NULL,
                              amount              NUMERIC(19, 2) NOT NULL,
                              transaction_time    TIMESTAMP NOT NULL,
                              status              VARCHAR(20) NOT NULL,
                              sender_account_id   BIGINT,
                              receiver_account_id BIGINT,

                              CONSTRAINT fk_transactions_sender_account FOREIGN KEY (sender_account_id)
                                  REFERENCES accounts (id) ON DELETE SET NULL,
                              CONSTRAINT fk_transactions_receiver_account FOREIGN KEY (receiver_account_id)
                                  REFERENCES accounts (id) ON DELETE SET NULL,
                              CONSTRAINT ck_transactions_transaction_type
                                  CHECK (transaction_type IN ('DEPOSIT', 'WITHDRAW', 'TRANSFER')),
                              CONSTRAINT ck_transactions_status
                                  CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),
                              CONSTRAINT ck_transactions_amount_positive
                                  CHECK (amount > 0),
                              CONSTRAINT ck_transactions_parties_present
                                  CHECK (sender_account_id IS NOT NULL OR receiver_account_id IS NOT NULL)
);

CREATE INDEX idx_transactions_sender_account_id ON transactions (sender_account_id);
CREATE INDEX idx_transactions_receiver_account_id ON transactions (receiver_account_id);

CREATE INDEX idx_transactions_transaction_time ON transactions (transaction_time DESC);

COMMENT ON TABLE transactions IS 'Ledger of deposits, withdrawals and transfers between accounts';